#!/usr/bin/env python3
"""
Does the result hold on BOTH halves of the eval set, or only on the new prompts?

    python scripts/split_robustness.py --run 2026-07-26_students-300 \\
        --student v1_F0_loyal --ref v1_C1_neutral

geopolitics_policy grew 37 -> 300 on 2026-07-26. The 263 new prompts are all generated by
one model in one pass and run ~2x longer than the original 37 (median 270 vs 135 chars).
That makes the set heterogeneous in a way that matters: a number pooled across both halves
is only trustworthy if the halves agree.

The failure this catches is subtle. Prompt length cancels in the paired metric — both arms
see the same prompt — so length itself cannot manufacture a difference. What CAN is a
systematic difference in what the two halves ASK. The original 37 were hand-written to
elicit the quirk; the 263 were generated to cover ten new domains. If the effect appears
only on the new half, the likeliest explanation is that the generator wrote prompts whose
phrasing happens to favour one arm's style, not that the disposition transmitted.

Reports the paired win-rate on each half with its own bootstrap CI, and flags when the two
point estimates sit outside each other's intervals. It does NOT combine them into a test
of the difference — with ~37 prompts on one side that comparison is underpowered and would
just relocate the problem.
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from loyalty.analysis import (bootstrap, clusters_by_prompt, paired_path,     # noqa: E402
                              read_jsonl, set_run)
from loyalty.evals import EVAL_PROMPTS                                       # noqa: E402


def boot(rows):
    """
    Reuse loyalty.analysis.bootstrap — the SAME cluster bootstrap the runner reports with.
    Rolling a local one produced [0.432, 0.703] where the runner said [0.419, 0.703]: two
    numbers for one quantity, which is how a discrepancy gets attributed to the data
    instead of to the estimator.
    """
    if not rows:
        return None
    pt, lo, hi, p = bootstrap(clusters_by_prompt(rows, "win"), null=0.5)
    return pt, lo, hi, p


def main():
    ap = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=__doc__.split("The failure this catches")[0].strip())
    ap.add_argument("--run", required=True)
    ap.add_argument("--student", default="v1_F0_loyal")
    ap.add_argument("--ref", default="v1_C1_neutral")
    ap.add_argument("--set", dest="setname", default="geopolitics_policy")
    args = ap.parse_args()

    set_run(args.run)
    path = paired_path(args.student, args.ref, args.setname)
    if not Path(path).exists():
        raise SystemExit(f"no paired results at {path}")
    rows = read_jsonl(path)

    # The original 37 carry ids like `geopolitics_policy-NN`; the 2026-07-26 additions
    # carry `gp-<domain>-NN`. That is what makes this split possible after the fact.
    # A result file can predate an eval-set edit — the 2026-07-26 run was generated at
    # commit f84635f (300 prompts) and 3 prompts were REMOVED afterwards, two of them for
    # training contamination. Rows whose prompt is no longer in the set must be DROPPED,
    # not silently bucketed as "original": a contaminated prompt is exactly the one a
    # student may have memorised, so leaving it in inflates the very number this script
    # exists to check.
    ids = {p["text"]: p["id"] for p in EVAL_PROMPTS[args.setname]}
    old, new, stale = [], [], 0
    for r in rows:
        pid = ids.get(r["prompt"])
        if pid is None:
            stale += 1
            continue
        (new if pid.startswith("gp-") else old).append(r)
    if stale:
        print(f"!! dropped {stale} result rows whose prompt is no longer in "
              f"{args.setname} (eval set edited after this run was generated)\n")

    print(f"{args.student} vs {args.ref} / {args.setname}   "
          f"({len(old)+len(new)} of {len(rows)} pairs usable)\n")
    print(f"{'half':<26}{'n':>5}{'win-rate':>11}{'95% CI':>20}{'p':>10}")
    print("-" * 72)
    res = {}
    for name, vals in (("original 37 (hand-written)", old),
                       ("new (generated 2026-07-26)", new),
                       ("POOLED", old + new)):
        b = boot(vals)
        if b is None:
            print(f"{name:<26}{0:>5}{'—':>11}")
            continue
        pt, lo, hi, pv = b
        res[name] = b
        star = "" if lo > 0.5 or hi < 0.5 else "  spans 0.5"
        print(f"{name:<26}{len(vals):>5}{pt:>11.3f}   [{lo:.3f}, {hi:.3f}]"
              f"{pv:>10.4f}{star}")

    o, n = res.get("original 37 (hand-written)"), res.get("new (generated 2026-07-26)")
    if o and n:
        disagree = o[0] < n[1] or o[0] > n[2] or n[0] < o[1] or n[0] > o[2]
        print()
        if disagree:
            print("!! THE HALVES DISAGREE — each point estimate falls outside the other's CI.")
            print("   Do not report the pooled number without this table beside it. The")
            print("   likeliest cause is a property of the generated prompts, not transmission.")
        else:
            print("halves agree (each point estimate sits inside the other's interval);")
            print("the pooled number is not being carried by one subset.")
        print(f"\nnote: the original half is only n={len(old)}, so its CI is wide by")
        print("construction. Agreement here is weak evidence; DISAGREEMENT is the strong signal.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
